FROM python:3.6

RUN apt install git 
RUN git clone https://github.com/j3mfilho/TechnologyInternetSystems.git


WORKDIR /TechnologyInternetSystems/SO/Teste/

ENTRYPOINT ["python3"]
CMD ["Teste.py"]
